version: "3.3"

services:
  db:
    build:  ./mysql/
    image: vivekmt2019137/kubesql:v1
    restart: always
    networks:
      - database
    # environment:
    #   - MYSQL_USER=iiitbspring
    #   - MYSQL_PASSWORD=iiitbspring
    #   - MYSQL_ROOT_PASSWORD=qwertyuiop
  
  apimonitor:
    build: ./apiMonitor/
    image: vivekmt2019137/kubeapimonitor:v1
    networks:
      - api
    # ports:
    #   - "8585:8585"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock

  apiserver:
    build: ./apiServer/
    image: vivekmt2019137/kubeapiserver:v1
    depends_on:
      - db
    networks:
      - database
      - api
    # environment:
    #   - username=iiitbspring
    #   - password=iiitbspring
    #   - DB_URL=jdbc:mysql://db:3306?useSSL=false&serverTimezone=UTC
    #   - monitor=http://apimonitor:8585
    ports:
      - "8686:8686"

networks:
  database:
  api: